# Generated by Django 6.0.7 on 2026-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_tag_alter_post_image_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
